# Generated by Django 5.2.7 on 2025-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('max_stock', models.IntegerField()),
                ('row', models.IntegerField()),
                ('level', models.IntegerField()),
                ('box', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
