# Generated by Django 5.2.7 on 2025-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_item_box_alter_item_level_alter_item_max_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='device_mac',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
